apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{.Release.Name}}
spec:
  type: NodePort
  ports:
  - port: 80
#    targetPort: 8080
    targetPort: 80
    protocol: TCP 
  selector:
    app: {{.Release.Name}}
