apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: arc-k8s-demo
spec:
  releaseName: arc-k8s-demo-2
  chart:
    git: https://github.com/nitinkansal1984/arc-helm-demo 
    ref: master
    path: charts/azure-arc-sample
  values:
    serviceName: arc-k8s-demo-2
